name: Discord Server Setup

# Security Features:
# - Only repository owner can trigger Discord setup
# - GLOWBOY token stored securely in GitHub Secrets
# - Manual approval required via environment protection
# - No unauthorized access to Discord bot token

on:
  workflow_dispatch:  # Manual trigger only (no automatic runs)
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'setup'
        type: choice
        options:
          - setup
          - update-webhooks
          - security-check

jobs:
  discord-setup:
    runs-on: ubuntu-latest
    # Security: Only allow repository owner to run Discord setup
    if: github.actor == github.repository_owner || github.actor == 'Severswoed'
    environment: discord-management  # Requires manual approval
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Discord dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py aiohttp
        
    - name: Validate Discord bot token
      run: |
        if [ -z "${{ secrets.GLOWBOY }}" ]; then
          echo "❌ GLOWBOY secret not found"
          echo "Please add your Discord bot token as a GitHub secret named 'GLOWBOY'"
          exit 1
        fi
        echo "✅ Discord bot token is configured"
        
    - name: Run Discord setup
      run: |
        echo "🤖 Running Discord setup with action: ${{ github.event.inputs.action }}"
        echo "👤 Authorized user: ${{ github.actor }}"
        echo "🔐 Using secure bot token from GitHub Secrets"
        
        cd discord
        python setup_discord.py
      env:
        GLOWBOY: ${{ secrets.GLOWBOY }}
        GITHUB_ACTIONS: "true"
        GITHUB_ACTOR: ${{ github.actor }}
        DISCORD_SETUP_ACTION: ${{ github.event.inputs.action }}
        
    - name: Security audit log
      run: |
        echo "📋 Discord Setup Security Audit"
        echo "================================"
        echo "Date: $(date)"
        echo "User: ${{ github.actor }}"
        echo "Action: ${{ github.event.inputs.action }}"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "================================"
        echo "✅ Discord setup completed successfully"
        echo "🛡️ No sensitive data exposed in logs"
